dataserv.lo: /root/workspace/phpsrc/ext/dataserv/dataserv.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/workspace/phpsrc/ext/dataserv $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/workspace/phpsrc/ext/dataserv/dataserv.c -o dataserv.lo 
$(phplibdir)/dataserv.la: ./dataserv.la
	$(LIBTOOL) --mode=install cp ./dataserv.la $(phplibdir)

./dataserv.la: $(shared_objects_dataserv) $(DATASERV_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_dataserv) $(DATASERV_SHARED_LIBADD)

